const legacyFrenchGradeOptions = [
  "4a",
  "4a/4a+",
  "4a+",
  "4a+/b",
  "4b",
  "4b/4b+",
  "4b+",
  "4b+/c",
  "4c",
  "4c/4c+",
  "4c+",
  "4c+/5a",
  "5a",
  "5a/5a+",
  "5a+",
  "5a+/b",
  "5b",
  "5b/5b+",
  "5b+",
  "5b+/c",
  "5c",
  "5c/5c+",
  "5c+",
  "5c+/6a",
  "6a",
  "6a/6a+",
  "6a+",
  "6a+/b",
  "6b",
  "6b/6b+",
  "6b+",
  "6b+/c",
  "6c",
  "6c/6c+",
  "6c+",
  "6c+/7a",
  "7a",
  "7a/7a+",
  "7a+",
  "7a+/b",
  "7b",
  "7b/7b+",
  "7b+",
  "7b+/c",
  "7c",
  "7c/7c+",
  "7c+",
  "7c+/8a",
  "8a",
  "8a/8a+",
  "8a+",
  "8a+/b",
  "8b",
  "8b/8b+",
  "8b+",
  "8b+/c",
  "8c",
  "8c/8c+",
  "8c+/9a",
  "9a",
  "9a/9a+",
  "9a+/b",
  "9b",
  "9b/9b+",
  "9b+",
  "9b+/c",
  "9c",
];
import type { TrainingSurface } from "@/lib/climbs-db";

export const settingsTabs: {
  key: "profil" | "zespol" | "zaawansowane";
  label: string;
  route: string;
}[] = [
  { key: "profil", label: "Profil", route: "/ustawienia/profil" },
  { key: "zespol", label: "Zespół", route: "/ustawienia/zespol" },
  {
    key: "zaawansowane",
    label: "Zaawansowane",
    route: "/ustawienia/zaawansowane",
  },
];

export const surfaceOptions: Array<{ value: TrainingSurface; label: string }> =
  [
    { value: "lina", label: "Lina" },
    { value: "baldy", label: "Baldy" },
    { value: "moon", label: "Moon" },
    { value: "chwytotablica", label: "Chwytotablica" },
    { value: "campus", label: "Campus" },
    { value: "spraywall", label: "Spraywall" },
    { value: "kilter", label: "Kilter" },
    { value: "silownia", label: "Siłownia" },
    { value: "bieznia", label: "Bieżnia" },
    { value: "rower", label: "Rower" },
    { value: "bieg", label: "Bieg" },
    { value: "treking", label: "Treking" },
  ];

export const frenchGradeOptions = [
  "4a",
  "4a/4a+",
  "4a+",
  "4a+/b",
  "4b",
  "4b/4b+",
  "4b+",
  "4b+/c",
  "4c",
  "4c/4c+",
  "4c+",
  "4c+/5a",
  "5a",
  "5a/5a+",
  "5a+",
  "5a+/b",
  "5b",
  "5b/5b+",
  "5b+",
  "5b+/c",
  "5c",
  "5c/5c+",
  "5c+",
  "5c+/6a",
  "6a",
  "6a/6a+",
  "6a+",
  "6a+/b",
  "6b",
  "6b/6b+",
  "6b+",
  "6b+/c",
  "6c",
  "6c/6c+",
  "6c+",
  "6c+/7a",
  "7a",
  "7a/7a+",
  "7a+",
  "7a+/b",
  "7b",
  "7b/7b+",
  "7b+",
  "7b+/c",
  "7c",
  "7c/7c+",
  "7c+",
  "7c+/8a",
  "8a",
  "8a/8a+",
  "8a+",
  "8a+/b",
  "8b",
  "8b/8b+",
  "8b+",
  "8b+/c",
  "8c",
  "8c/8c+",
  "8c+",
  "8c+/9a",
  "9a",
  "9a/9a+",
  "9a+",
  "9a+/b",
  "9b",
  "9b/9b+",
  "9b+",
  "9b+/c",
  "9c",
];
