--liquibase formatted sql

--changeset climberbook:001-initial-schema
create table sections (
  id uuid primary key,
  source_id uuid unique,
  name text not null,
  created_at timestamptz not null default now()
);

create table athletes (
  id uuid primary key,
  source_id uuid unique,
  name text not null,
  first_name text not null default '',
  last_name text not null default '',
  nick text not null default '',
  section_id uuid references sections(id) on delete set null,
  created_at timestamptz not null default now()
);

create table user_profiles (
  key text primary key,
  athlete_id uuid not null references athletes(id) on delete cascade,
  birth_date text not null default '',
  sex text not null default '',
  height_cm numeric,
  weight_kg numeric,
  updated_at timestamptz not null default now()
);

create table trainings (
  id uuid primary key,
  source_id uuid unique,
  athlete_id uuid not null references athletes(id) on delete cascade,
  date text not null,
  time text not null,
  duration_minutes integer not null,
  body_weight_kg numeric not null,
  age_years integer not null default 0,
  calories_burned integer not null default 0,
  attempts_count integer not null default 0,
  difficulty_notes text not null default '',
  difficulty_by_surface jsonb,
  protocol jsonb,
  wellbeing text not null default '',
  surfaces text[] not null default '{}',
  custom_session_type text,
  notes text not null default '',
  created_at timestamptz not null default now()
);

create index trainings_by_athlete on trainings(athlete_id);
create index trainings_by_date on trainings(date);
create index trainings_by_created_at on trainings(created_at);

create table ascents (
  id bigint generated by default as identity primary key,
  athlete_id uuid not null references athletes(id) on delete cascade,
  date text not null,
  source text not null,
  import_source text,
  route_name text not null,
  suggested_grade text not null default '',
  subjective_grade text not null default '',
  style text,
  notes text not null default '',
  created_at timestamptz not null default now()
);

create index ascents_by_athlete on ascents(athlete_id);
create index ascents_by_date on ascents(date);
create index ascents_by_source on ascents(source);

create table weight_entries (
  id bigint generated by default as identity primary key,
  athlete_id uuid not null references athletes(id) on delete cascade,
  date text not null,
  time text not null,
  weight_kg numeric not null,
  created_at timestamptz not null default now()
);

create index weight_entries_by_athlete on weight_entries(athlete_id);
create index weight_entries_by_date on weight_entries(date);

create table idempotency_keys (
  key text primary key,
  operation text not null,
  response jsonb not null,
  created_at timestamptz not null default now()
);

--rollback drop table if exists idempotency_keys;
--rollback drop table if exists weight_entries;
--rollback drop table if exists ascents;
--rollback drop table if exists trainings;
--rollback drop table if exists user_profiles;
--rollback drop table if exists athletes;
--rollback drop table if exists sections;