--liquibase formatted sql

--changeset climberbook:004-add-facilities-and-climbs
create table facilities (
  id uuid primary key,
  name text not null,
  created_at timestamptz not null default now()
);

create index facilities_by_created_at on facilities(created_at);

create table climbs (
  id bigint generated by default as identity primary key,
  athlete_id uuid not null references athletes(id) on delete cascade,
  name text not null,
  grade text not null default '',
  created_at timestamptz not null default now()
);

create index climbs_by_athlete on climbs(athlete_id);
create index climbs_by_created_at on climbs(created_at);

alter table trainings add column facility_name text;

alter table user_profiles
  add constraint user_profiles_athlete_id_unique unique (athlete_id);

--rollback alter table user_profiles drop constraint if exists user_profiles_athlete_id_unique;
--rollback alter table trainings drop column if exists facility_name;
--rollback drop table if exists climbs;
--rollback drop table if exists facilities;